#!/usr/bin/env ruby
#^syntax detection

cookbook 'yum', '3.2.2'
cookbook 'mysql'
cookbook 'php'
cookbook 'redisio'
cookbook 'memcached'
cookbook 'nginx', '2.7.4' # Latest to support yum 2.x cookbook
cookbook 'nodejs'
cookbook 'git'
cookbook 'elasticsearch'
cookbook 'jetty', :github => 'inviqa/chef-jetty'
cookbook 'solr', :github => 'inviqa/chef-solr'
cookbook 'chef-varnish', :github => 'inviqa/chef-varnish'
cookbook 'config-driven-helper', :github => 'inviqa/chef-config-driven-helper'

cookbook 'symfony-customizations', :path => './site-cookbooks/symfony'
